# Updated Starship Configuration for Aesthetic Look

format = """
$directory\
[](fg:#306b63 bg:#25322d)\
$git_branch\
$git_status\
[](fg:#25322d bg:#304238)\
$nodejs\
$rust\
$golang\
$php\
$fill\
$time\
\n$character"""

[fill]
symbol=" "

[directory]
style = "fg:#e3e5e5 bg:#306b63"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#27322d"
format = '[[ $symbol $branch ](fg:#5a9b8a bg:#27322d)]($style)'

[git_status]
style = "bg:#27322d"
format = '[[($all_status$ahead_behind )](fg:#5a9b8a bg:#27322d)]($style)'

[nodejs]
symbol = ""
style = "bg:#304238"
format = '[[ $symbol ($version) ](fg:#306b63 bg:#304238)]($style)'

[rust]
symbol = ""
style = "bg:#304238"
format = '[[ $symbol ($version) ](fg:#306b63 bg:#304238)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#304238"
format = '[[ $symbol ($version) ](fg:#306b63 bg:#304238)]($style)'

[php]
symbol = ""
style = "bg:#304238"
format = '[[ $symbol ($version) ](fg:#306b63 bg:#304238)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#304238"
format = '[[  $time ](fg:#5a9b8a bg:#304238)]($style)'

